import "./globals.css";
import { Rationale, Montserrat_Alternates } from "next/font/google";
import { StoreProvider } from "@/app/lib/store/StoreProvider";
import AuthProvider from "@/app/lib/store/AuthProvider";
import ErrorMsg from "./components/ui/ErrorMsg";
import NavigationWrapper from "./layout/navigation/NavigationWrapper";
import GlobalModal from "./components/containers/GlobalModal";
import Footer from "./layout/footer/Footer";

const rationale = Rationale({
  variable: "--font-rationale",
  subsets: ["latin"],
  weight: "400",
});

const montserratAlternates = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rationale.variable} ${montserratAlternates.variable} min-h-screen relative flex flex-col duration-300 bg-black text-gold`}
      >
        <StoreProvider>
          <AuthProvider>
            <NavigationWrapper />
            {children}
            <ErrorMsg />
            <GlobalModal />
            <Footer />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
