export const countries = [
  "United States",
  "United Kingdom",
  "Netherlands",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Belgium",
  "Switzerland",
  "Austria",
  "Ireland",
  "Portugal",
  "Greece",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Slovakia",
  "Slovenia",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Australia",
  "New Zealand",
  "Canada",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Ecuador",
  "Bolivia",
  "Paraguay",
  "Uruguay",
  "Japan",
  "South Korea",
  "China",
  "India",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Indonesia",
  "Philippines",
  "Hong Kong",
  "Taiwan",
  "Israel",
  "UAE",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "South Africa",
  "Nigeria",
  "Egypt",
  "Morocco",
  "Tunisia",
  "Algeria",
  "Kenya",
  "Ghana",
  "Ethiopia",
  "Tanzania",
  "Uganda",
  "Rwanda",
  "Senegal",
  "Cote d'Ivoire",
  "Cameroon",
  "Angola",
  "Mozambique",
  "Zambia",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "Madagascar",
  "Mauritius",
  "Seychelles",
  "Comoros",
  "Djibouti",
  "Eritrea",
  "Somalia",
  "Sudan",
  "South Sudan",
  "Chad",
  "Niger",
  "Mali",
  "Burkina Faso",
  "Benin",
  "Togo",
  "Liberia",
  "Sierra Leone",
  "Guinea",
  "Guinea-Bissau",
  "Gambia",
  "Cape Verde",
  "Sao Tome and Principe",
  "Equatorial Guinea",
  "Gabon",
  "Congo",
  "Democratic Republic of the Congo",
  "Central African Republic",
  "Burundi",
  "Malawi",
  "Lesotho",
  "Eswatini",
  "Mauritania",
  "Western Sahara",
  "Libya",
  "Lebanon",
  "Jordan",
  "Syria",
  "Iraq",
  "Iran",
  "Afghanistan",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Bhutan",
  "Myanmar",
  "Laos",
  "Cambodia",
  "Brunei",
  "East Timor",
  "Papua New Guinea",
  "Fiji",
  "Solomon Islands",
  "Vanuatu",
  "Samoa",
  "Tonga",
  "Kiribati",
  "Tuvalu",
  "Nauru",
  "Marshall Islands",
  "Palau",
  "Micronesia",
  "Northern Mariana Islands",
  "Guam",
  "American Samoa",
  "Cook Islands",
  "Niue",
  "Tokelau",
  "Wallis and Futuna",
  "French Polynesia",
  "New Caledonia",
  "Pitcairn Islands",
  "Norfolk Island",
  "Christmas Island",
  "Cocos Islands",
  "Heard Island and McDonald Islands",
  "French Southern Territories",
  "British Indian Ocean Territory",
  "South Georgia and the South Sandwich Islands",
  "Bouvet Island",
  "Antarctica",
];
